version: '3.7'
services:
  serve:
    build:
      context: serve
    environment:
      FLASK_APP: app
      FLASK_ENV: production
    ports:
    - 5000:5000

  playground27:
    restart: on-failure
    depends_on:
      serve:
        condition: service_started
    volumes:
    - ./results:/results
    build:
      context: playground
      args:
        PYTHON_VER: 2.7

  playground38:
    restart: on-failure
    depends_on:
      serve:
        condition: service_started
    volumes:
      - ./results:/results
    build:
      context: playground
      args:
        PYTHON_VER: 3.8
